[package]
name = "crasher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
thiserror = "1"
rand = "0.8.5"
clap = { version = "4.3.0", features = ["derive"] }
tokio = {version = "1.28.1", features = ["full"]}
qdrant-client = "1.2.0"
ctrlc = "3.3.1"
log = "0.4.17"
env_logger = "0.10.0"