[package]
name = "crasher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
thiserror = "1"
rand = "0.8.5"
clap = { version = "4.5.1", features = ["derive"] }
tokio = {version = "1.36.0", features = ["full"]}
qdrant-client = "1.7.0"
ctrlc = "3.4.2"
log = "0.4.20"
env_logger = "0.11.2"